---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - В каталоге должно быть выведено название, рейтинг, цена со скидкой и без нее для каждого товара
  - На странице товара должно быть выведено название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность пользоваться постраничным выводом, просматривая каталог товаров
  - Сайт должен иметь мобильную версию
  - Интернет-магазин должен иметь SPA-приложение, которое не перезагружает страницу
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность после добавления товара в корзину продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность на странице корзины удалить товар из корзины и продолжить выбирать товары в 
    каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Текст должен быть читаемым, контрастным
  - Значения в столбцах должны быть выравнены по одной линии
  - Цена без скидки и цена со скидкой не должны быть разделены другими элементами
  - Сайт не должен виснуть при переходе по страницам
